_target_: torch.optim.Adam

# these are default parameters for Adam
lr: 0.001
eps: 1e-08
weight_decay: 0
betas: [0.9, 0.999]


# _convert_ is hydra syntax needed to make betas parameter work, learn more here:
# https://hydra.cc/docs/next/advanced/instantiate_objects/overview/#parameter-conversion-strategies
_convert_: "partial"
