name: myenv

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - notebook
  - ipython
  - cudatoolkit
  - pytorch=1.8.1
  - torchvision=0.9.1
  - pip:
      - -r requirements.txt
