# @package _global_

# debug mode sets name of the logging folder to 'logs/debug/...'
# enables trainer debug options
# also sets level od command line logger to DEBUG
# example usage:
# `python run.py mode=debug`

defaults:
  - override /trainer: debug.yaml

debug_mode: True

hydra:
  # sets level of all command line loggers to 'DEBUG'
  verbose: True

  # https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
  # use this to set level of only chosen command line loggers to 'DEBUG'
  # verbose: [src.train, src.utils]

  run:
    dir: logs/debug/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/debug/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

# disable rich config printing, since it will be already printed by hydra when `verbose: True`
print_config: False
