# https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.EarlyStopping.html#pytorch_lightning.callbacks.EarlyStopping

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: ???
  min_delta: 0.
  patience: 3
  verbose: False
  mode: "min"
  strict: True
  check_finite: True
  stopping_threshold: null
  divergence_threshold: null
  check_on_train_epoch_end: null
  log_rank_zero_only: False
