# https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.RichModelSummary.html#pytorch_lightning.callbacks.RichModelSummary

model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: 1
