# https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.RichProgressBar.html#pytorch_lightning.callbacks.RichProgressBar

rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar
