<<<<<<< HEAD
# https://pytorch-lightning.readthedocs.io/en/latest/api/lightning.callbacks.RichProgressBar.html
=======
# https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.RichProgressBar.html
>>>>>>> main

rich_progress_bar:
  _target_: lightning.pytorch.callbacks.RichProgressBar
