defaults:
    - default.yaml


watch_model:
    _target_: src.callbacks.wandb_callbacks.WatchModelWithWandb
    log: "all"
    log_freq: 100


upload_code_as_artifact:
    _target_: src.callbacks.wandb_callbacks.UploadCodeToWandbAsArtifact
    code_dir: ${work_dir}/src


upload_ckpts_as_artifact:
    _target_: src.callbacks.wandb_callbacks.UploadCheckpointsToWandbAsArtifact
    ckpt_dir: "checkpoints/"
    upload_best_only: True


log_f1_precision_recall_heatmap:
    _target_: src.callbacks.wandb_callbacks.LogF1PrecRecHeatmapToWandb


log_confusion_matrix:
    _target_: src.callbacks.wandb_callbacks.LogConfusionMatrixToWandb


log_images_with_predictions:
    _target_: src.callbacks.wandb_callbacks.ImagePredictionLogger
    num_samples: 8
