# @package _global_
#
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: long
    cpus_per_task: 4
    mem_gb: 20
    gres: gpu:1
    timeout_min: 2000
    array_parallelism: 10 # max num of tasks to run in parallel (via job array)
    setup:
      - "module purge"
      - "module load miniconda/3"
      - "conda activate structure_recovery"
