# @package _global_
#
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: gpu
    cpus_per_task: 2
    #gpus_per_node: 1
    tasks_per_node: 1
    nodes: 1
    mem_gb: 20
    #mem_per_cpu: 20G
    #mem_per_gpu: 20
    gres: gpu:1
    timeout_min: 2000
    array_parallelism: 15 # max num of tasks to run in parallel (via job array)
    #setup:
    #  - "module purge"
    #  - "module load miniconda/3"
    #  - "conda init"
    #  - "conda activate structure_recovery_gpu"
