name: Tests

on:
  push:
    branches: [release/1.4]
  pull_request:
    branches: [release/1.4]

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7"]

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: List dependencies
        run: |
          python -m pip list

      - name: Run tests with pytest
        run: |
          pytest -v

  # check code formatting
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3

  # check common spelling mistakes
  misspell-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: sobolevn/misspell-fixer-action@master
